#object that store enviroments variables that could be have sensitive data like a password
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    #meant that we can use arbitrary key pair values
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM= #postgres base64
  POSTGRES_USER: cG9zdGdyZXM= #postgres base64
  POSTGRES_PASSWORD: cXdlcnR5 #qwerty
